### PR TITLE
Resolving Jumbotron Issue

### PR DESCRIPTION
**Pull request by HashirGJ8842**

### CODE REVIEW

**Comment by HashirGJ8842** [comment]
image

**Comment by HashirGJ8842** [comment]
You mean to align the list items towards left?

**Comment by ayaankhan98** [comment]
Hope this will make everything clear
Screenshot from 2020-01-18 23-21-48

**Comment by HashirGJ8842** [comment]
Yeah👍

**Comment by HashirGJ8842** [comment]
image

**Comment by HashirGJ8842** [comment]
Please suggest any other changes you all wish to see.

**Comment by ayaankhan98** [comment]
yeah that looks nice, well leave this for now we will see create another issue if we wish to implement anything else for now it seems to be resolved

**Pull request merged**
